// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn5e4gefo4_iJ3OnZ_QU-uCTT-Uas4SjI',
    appId: '1:1053962346056:web:64282ec035c34c59a6827d',
    messagingSenderId: '1053962346056',
    projectId: 'myprojectfirebas-86a91',
    authDomain: 'myprojectfirebas-86a91.firebaseapp.com',
    storageBucket: 'myprojectfirebas-86a91.firebasestorage.app',
    measurementId: 'G-VQ0TYN5Z29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuu5qjZZ9BUah73ihiKfZj8pwKRCElOlQ',
    appId: '1:1053962346056:android:759ef7f598de8e77a6827d',
    messagingSenderId: '1053962346056',
    projectId: 'myprojectfirebas-86a91',
    storageBucket: 'myprojectfirebas-86a91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKflTj5cNCKbdthQdUh0B0b1XIFBIgTo',
    appId: '1:1053962346056:ios:a474b775443f6ec0a6827d',
    messagingSenderId: '1053962346056',
    projectId: 'myprojectfirebas-86a91',
    storageBucket: 'myprojectfirebas-86a91.firebasestorage.app',
    iosClientId:
        '1053962346056-vfh4lbd4ccevc88tpdfholrcuru1tdvf.apps.googleusercontent.com',
    iosBundleId: 'com.bakulandfrozen.bakulanDFrozen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtKflTj5cNCKbdthQdUh0B0b1XIFBIgTo',
    appId: '1:1053962346056:ios:a474b775443f6ec0a6827d',
    messagingSenderId: '1053962346056',
    projectId: 'myprojectfirebas-86a91',
    storageBucket: 'myprojectfirebas-86a91.firebasestorage.app',
    iosClientId:
        '1053962346056-vfh4lbd4ccevc88tpdfholrcuru1tdvf.apps.googleusercontent.com',
    iosBundleId: 'com.bakulandfrozen.bakulanDFrozen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARFduj3jSwhtwWR025lUcOZjaCuFFuTs4',
    appId: '1:1053962346056:web:0c030754f1bf99f9a6827d',
    messagingSenderId: '1053962346056',
    projectId: 'myprojectfirebas-86a91',
    authDomain: 'myprojectfirebas-86a91.firebaseapp.com',
    storageBucket: 'myprojectfirebas-86a91.firebasestorage.app',
    measurementId: 'G-4ME4TZMCLD',
  );
}
